// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.Infrastructure.Persistence;

#nullable disable

namespace QuizApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241024174245_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApp.Domain.Entities.Option", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionChoice")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuestionId", "OptionChoice");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            QuestionId = new Guid("93bd883c-cd30-4aa1-8d22-ebe61f852cac"),
                            OptionChoice = "A",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionText = "Medan"
                        },
                        new
                        {
                            QuestionId = new Guid("93bd883c-cd30-4aa1-8d22-ebe61f852cac"),
                            OptionChoice = "B",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionText = "Bandung"
                        },
                        new
                        {
                            QuestionId = new Guid("93bd883c-cd30-4aa1-8d22-ebe61f852cac"),
                            OptionChoice = "C",
                            ImageUrl = "",
                            IsCorrect = true,
                            OptionText = "Jakarta"
                        });
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuizId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = new Guid("93bd883c-cd30-4aa1-8d22-ebe61f852cac"),
                            QuestionText = "What is the capital of Indonesia?",
                            QuizId = new Guid("98dc1ade-7d39-42dc-ab8b-ee9ecedd590c")
                        });
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QuizId = new Guid("98dc1ade-7d39-42dc-ab8b-ee9ecedd590c"),
                            Title = "Mock Quiz"
                        });
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<Guid>("QuestionId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResponseId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.HasIndex("QuestionId", "OptionChoice");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuizId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("QuizId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = new Guid("e8af45fb-b512-467f-b404-577cda511471"),
                            EndDate = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            QuizId = new Guid("98dc1ade-7d39-42dc-ab8b-ee9ecedd590c"),
                            StartDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3f2aa04d-319f-4476-9884-2376dffa5bba"),
                            FullName = "Admin",
                            Initial = "admin",
                            Password = "dummypassword",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("6dcadd85-1a13-44db-ac5e-935d37e27703"),
                            FullName = "Daniel Adamlu",
                            Initial = "NL23-2",
                            Password = "dummypassword",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.UserSchedule", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("UserSchedules");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6dcadd85-1a13-44db-ac5e-935d37e27703"),
                            ScheduleId = new Guid("e8af45fb-b512-467f-b404-577cda511471"),
                            Status = "Incomplete"
                        });
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.UserScore", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("UserId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("UserScores");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Option", b =>
                {
                    b.HasOne("QuizApp.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Question", b =>
                {
                    b.HasOne("QuizApp.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Response", b =>
                {
                    b.HasOne("QuizApp.Domain.Entities.Question", "Question")
                        .WithOne("Response")
                        .HasForeignKey("QuizApp.Domain.Entities.Response", "QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizApp.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Responses")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizApp.Domain.Entities.User", "User")
                        .WithMany("Responses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizApp.Domain.Entities.Option", "Option")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId", "OptionChoice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("QuizApp.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Schedules")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.UserSchedule", b =>
                {
                    b.HasOne("QuizApp.Domain.Entities.Schedule", "Schedule")
                        .WithMany("UserSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizApp.Domain.Entities.User", "User")
                        .WithMany("UserSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.UserScore", b =>
                {
                    b.HasOne("QuizApp.Domain.Entities.Schedule", "Schedule")
                        .WithMany("UserScores")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizApp.Domain.Entities.User", "User")
                        .WithMany("Scores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Option", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("UserSchedules");

                    b.Navigation("UserScores");
                });

            modelBuilder.Entity("QuizApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Scores");

                    b.Navigation("UserSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
